export default {
  boundaries: [
    // These are needed for every version (year) of every geography.
    // Every detail level is included, for the benefit of creating vector tiles.
    // BFE files are used for calculating accurate lookups.
    {name: "ctry22_bfe", id: "Countries_December_2022_UK_BFE", code: "CTRY"},
    {name: "ctry22_bfc", id: "Countries_December_2022_UK_BFC", code: "CTRY"},
    {name: "ctry22_bgc", id: "Countries_December_2022_UK_BGC", code: "CTRY"},
    {name: "ctry22_buc", id: "Countries_December_2022_UK_BUC", code: "CTRY"},
    {name: "rgn22_bfe", id: "Regions_December_2022_EN_BFE", code: "RGN"},
    {name: "rgn22_bfc", id: "Regions_December_2022_EN_BFC", code: "RGN"},
    {name: "rgn22_bgc", id: "Regions_December_2022_EN_BGC", code: "RGN"},
    {name: "rgn22_buc", id: "Regions_December_2022_EN_BUC", code: "RGN"},
    {name: "cauth22_bfe", id: "Combined_Authorities_December_2022_EN_BFE", code: "CAUTH"},
    {name: "cauth22_bfc", id: "Combined_Authorities_December_2022_EN_BFC", code: "CAUTH"},
    {name: "cauth22_bgc", id: "Combined_Authorities_December_2022_EN_BGC", code: "CAUTH"},
    {name: "cauth22_buc", id: "Combined_Authorities_December_2022_EN_BUC", code: "CAUTH"},
    {name: "cauth24_bfe", id: "Combined_Authorities_May_2023_Boundaries_EN_BFE", code: "CAUTH"},
    {name: "cauth24_bfc", id: "Combined_Authorities_May_2023_Boundaries_EN_BFC", code: "CAUTH"},
    {name: "cauth24_bgc", id: "Combined_Authorities_May_2023_Boundaries_EN_BGC", code: "CAUTH"},
    {name: "cauth24_buc", id: "Combined_Authorities_May_2023_Boundaries_EN_BUC", code: "CAUTH"},
    {name: "cauth25_bfe", id: "CAUTH_MAY_2025_EN_BFE", code: "CAUTH"},
    {name: "cauth25_bfc", id: "CAUTH_MAY_2025_EN_BFC", code: "CAUTH"},
    {name: "cauth25_bgc", id: "CAUTH_MAY_2025_EN_BGC", code: "CAUTH"},
    {name: "cauth25_buc", id: "CAUTH_MAY_2025_EN_BSC", code: "CAUTH"}, // !!! This was BUC in other years !!!
    {name: "cty22_bfe", id: "Counties_December_2022_EN_BFE", code: "CTY"},
    {name: "cty22_bfc", id: "Counties_December_2022_EN_BFC", code: "CTY"},
    {name: "cty22_bgc", id: "Counties_December_2022_EN_BGC", code: "CTY"},
    {name: "cty22_buc", id: "Counties_December_2022_EN_BUC", code: "CTY"},
    {name: "cty23_bfe", id: "Counties_May_2023_Boundaries_EN_BFE", code: "CTY"},
    {name: "cty23_bfc", id: "Counties_May_2023_Boundaries_EN_BFC", code: "CTY"},
    {name: "cty23_bgc", id: "Counties_May_2023_Boundaries_EN_BGC", code: "CTY"},
    {name: "cty23_buc", id: "Counties_May_2023_Boundaries_EN_BUC", code: "CTY"},
    {name: "ltla22_bfe", id: "LAD_DEC_2022_UK_BFE_V2", code: "LAD"},
    {name: "ltla22_bfc", id: "Local_Authority_Districts_December_2022_Boundaries_UK_BFC", code: "LAD"},
    {name: "ltla22_bgc", id: "Local_Authority_Districts_December_2022_Boundaries_UK_BGC", code: "LAD"},
    {name: "ltla22_buc", id: "Local_Authority_Districts_December_2022_Boundaries_UK_BUC", code: "LAD"},
    {name: "ltla23_bfe", id: "Local_Authority_Districts_May_2023_UK_BFE", code: "LAD"},
    {name: "ltla23_bfc", id: "Local_Authority_Districts_May_2023_UK_BFC", code: "LAD"},
    {name: "ltla23_bgc", id: "Local_Authority_Districts_May_2023_UK_BGC", code: "LAD"},
    {name: "ltla23_buc", id: "Local_Authority_Districts_May_2023_UK_BUC", code: "LAD"},
    {name: "ltla25_bfe", id: "LAD_MAY_2025_UK_BFE", code: "LAD"},
    {name: "ltla25_bfc", id: "LAD_MAY_2025_UK_BFC", code: "LAD"},
    {name: "ltla25_bgc", id: "LAD_MAY_2025_UK_BGC", code: "LAD"},
    {name: "ltla25_buc", id: "LAD_MAY_2025_UK_BSC", code: "LAD"}, // !!! This was BUC in other years !!!  
    {name: "wpc22_bfe", id: "PCON_DEC_2022_UK_BFE_V2", code: "PCON"},
    {name: "wpc22_bfc", id: "Westminster_Parliamentary_Constituencies_Dec_2022_UK_BFC", code: "PCON"},
    {name: "wpc22_bgc", id: "Westminster_Parliamentary_Constituencies_Dec_2022_UK_BGC", code: "PCON"},
    {name: "wpc22_buc", id: "Westminster_Parliamentary_Constituencies_Dec_2022_UK_BUC", code: "PCON"},
    {name: "wpc24_bfe", id: "Westminster_Parliamentary_Constituencies_July_2024_Boundaries_UK_BFE", code: "PCON"},
    {name: "wpc24_bfc", id: "Westminster_Parliamentary_Constituencies_July_2024_Boundaries_UK_BFC", code: "PCON"},
    {name: "wpc24_bgc", id: "Westminster_Parliamentary_Constituencies_July_2024_Boundaries_UK_BGC", code: "PCON"},
    {name: "wpc24_buc", id: "Westminster_Parliamentary_Constituencies_July_2024_Boundaries_UK_BUC", code: "PCON"},
    {name: "sener22_bfe", id: "Senedd_Cymru_Electoral_Regions_December_2022_WA_BFE", code: "SENER"},
    {name: "sener22_bfc", id: "Senedd_Cymru_Electoral_Regions_December_2022_WA_BFC", code: "SENER"},
    {name: "sener22_bgc", id: "Senedd_Cymru_Electoral_Regions_December_2022_WA_BGC", code: "SENER"},
    {name: "sener22_buc", id: "Senedd_Cymru_Electoral_Regions_December_2022_WA_BUC", code: "SENER"},
    {name: "senc22_bfe", id: "Senedd_Cymru_Constituencies_December_2022_Boundaries_WA_BFE", code: "SENC"},
    {name: "senc22_bfc", id: "Senedd_Cymru_Constituencies_December_2022_Boundaries_WA_BFC", code: "SENC"},
    {name: "senc22_bgc", id: "Senedd_Cymru_Constituencies_December_2022_Boundaries_WA_BGC", code: "SENC"},
    {name: "senc22_buc", id: "Senedd_Cymru_Constituencies_December_2022_Boundaries_WA_BUC", code: "SENC"},
    {name: "par22_bfe", id: "Parishes_Decemeber_2022_EW_BFE", code: "PAR"},
    {name: "par22_bfc", id: "Parishes_December_2022_EW_BFC", code: "PAR"},
    {name: "par22_bgc", id: "Parishes_December_2022_EW_BGC", code: "PAR"},
    {name: "par22_bsc", id: "Parishes_December_2022_EW_BSC", code: "PAR"},
    {name: "wd22_bfe", id: "Wards_December_2022_Boundaries_GB_BFE", code: "WD"},
    {name: "wd22_bfc", id: "Wards_December_2022_Boundaries_GB_BFC", code: "WD"},
    {name: "wd22_bgc", id: "Wards_December_2022_Boundaries_GB_BGC", code: "WD"},
    {name: "wd22_bsc", id: "Wards_December_2022_Boundaries_GB_BSC", code: "WD"},
    {name: "wd23_bfe", id: "WD_MAY_2023_UK_BFE", code: "WD"},
    {name: "wd23_bfc", id: "WD_MAY_2023_UK_BFC", code: "WD"},
    {name: "wd23_bgc", id: "WD_MAY_2023_UK_BGC", code: "WD"},
    {name: "wd23_bsc", id: "WD_MAY_2023_UK_BSC", code: "WD"},
    {name: "wd24_bfe", id: "Wards_May_2024_Boundaries_UK_BFE", code: "WD"},
    {name: "wd24_bfc", id: "Wards_May_2024_Boundaries_UK_BFC", code: "WD"},
    {name: "wd24_bgc", id: "Wards_May_2024_Boundaries_UK_BGC", code: "WD"},
    {name: "wd24_bsc", id: "Wards_May_2024_Boundaries_UK_BSC", code: "WD"},
    {name: "wd25_bfe", id: "WD_MAY_2025_UK_BFE", code: "WD"},
    {name: "wd25_bfc", id: "WD_MAY_2025_UK_BFC", code: "WD"},
    {name: "wd25_bgc", id: "WD_MAY_2025_UK_BGC", code: "WD"},
    {name: "wd25_bsc", id: "WD_MAY_2025_UK_BSC", code: "WD"},
    {name: "ttwa11_bfe", id: "Travel_to_Work_Areas_Dec_2011_FEB_in_United_Kingdom_2022", code: "TTWA"},
    {name: "ttwa11_bfc", id: "Travel_to_Work_Areas_Dec_2011_FCB_in_United_Kingdom_2022", code: "TTWA"},
    {name: "ttwa11_bgc", id: "Travel_to_Work_Areas_Dec_2011_GCB_in_United_Kingdom_2022", code: "TTWA"},
    {name: "ttwa11_buc", id: "Travel_to_Work_Areas_Dec_2011_UGCB_in_United_Kingdom_2022", code: "TTWA"},
    {name: "bua22_bfc", id: "BUA_2022_GB", code: "BUA"},
    {name: "msoa21_bfe", id: "Middle_Layer_Super_Output_Areas_2021_EW_BFE_V6", code: "MSOA"},
    {name: "msoa21_bfc", id: "Middle_Layer_Super_Output_Areas_Dec_2021_Boundaries_Full_Clipped_EW_BFC_2022", code: "MSOA"},
    {name: "msoa21_bgc", id: "MSOA_Dec_2021_Boundaries_Generalised_Clipped_EW_BGC_2022", code: "MSOA"},
    {name: "msoa21_bsc", id: "MSOA_2021_EW_BSC", code: "MSOA"},
    {name: "lsoa21_bfe", id: "Lower_Layer_Super_Output_Area_2021_EW_BFE_V8", code: "LSOA"},
    {name: "lsoa21_bfc", id: "LSOA_Dec_2021_Boundaries_Full_Clipped_EW_BFC_2022", code: "LSOA"},
    {name: "lsoa21_bgc", id: "LSOA_Dec_2021_Boundaries_Generalised_Clipped_EW_BGC_V2", code: "LSOA"},
    {name: "lsoa21_bsc", id: "LSOA_2021_EW_BSC", code: "LSOA"},
    {name: "oa21_bfe", id: "Output_Areas_2021_EW_BFE_V8", code: "OA"},
    {name: "oa21_bfc", id: "Output_Areas_Dec_2021_Boundaries_Full_Clipped_EW_BFC_2022", code: "OA"},
    {name: "oa21_bgc", id: "Output_Areas_Dec_2021_Boundaries_Generalised_Clipped_EW_BGC_2022", code: "OA"},
  ],
  centroids: [
    {name: "oa21_pwc", id: "Output_Areas_2021_PWC_V3", code: "OA"},
    {name: "lsoa21_pwc", id: "LLSOA_Dec_2021_PWC_for_England_and_Wales_2022", code: "LSOA"},
    {name: "msoa21_pwc", id: "Middle_Super_Output_Areas_DEC_2021_EW_PWC", code: "MSOA"},
  ],
  census: [
    // This is a frozen Census 2021 lookup for interfacing with the Nomis API
    {name: "oa21_lsoa21_msoa21_ltla22.csv", id: "b9ca90c10aaa4b8d9791e9859a38ca67_0", fields: ["OA21CD", "LSOA21CD", "MSOA21CD", "LAD22CD"], names: ["oa21cd", "lsoa21cd", "msoa21cd", "ltla22cd"]},
  ],
  other: [
    {name: "msoa_names.csv", href: "https://houseofcommonslibrary.github.io/msoanames/MSOA-Names-Latest2.csv"}
  ],
};