export default [
  {z: 0, detail: ["buc"]},
  {z: 1, detail: ["buc"]},
  {z: 2, detail: ["buc"]},
  {z: 3, detail: ["buc"]},
  {z: 4, detail: ["buc"]},
  {z: 5, detail: ["buc"]},
  {z: 6, detail: ["bsc", "buc"]},
  {z: 7, detail: ["bsc", "buc"]},
  {z: 8, detail: ["bgc"]},
  {z: 9, detail: ["bgc"]},
  {z: 10, detail: ["bgc"]},
  {z: 11, detail: ["bgc"]},
  {z: 12, detail: ["bfc"]},
];